apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nguiland-ops-helm
  namespace: cicd
spec:
  interval: 1m
  url: ssh://github.com/biya-bi/nguiland-ops-helm.git
  ref:
    branch: develop
  secretRef:
    name: ssh-credentials
