apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nguiland-io-utils
  namespace: ${ENVIRONMENT}
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: ssh-credentials
  url: ssh://github.com/biya-bi/nguiland-io-utils.git
