apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dependencies.yaml
  - docker.yaml
  - dto.yaml
  - io-utils.yaml
  - ms-parent.yaml
  - orm.yaml
  - rest.yaml
  - tekton.yaml
  - web-oauth2.yaml
