apiVersion: cicd.nguiland.io/v1alpha1
kind: DependencyGraph
metadata:
  name: lib
  namespace: maven
spec:
  repositories:
    - name: nguiland-dependencies
    - name: nguiland-dto
      dependencies:
        - name: nguiland-dependencies
    - name: nguiland-io-utils
      dependencies:
        - name: nguiland-dependencies
    - name: nguiland-ms-parent
      dependencies:
        - name: nguiland-dependencies
    - name: nguiland-orm
      dependencies:
        - name: nguiland-dependencies
    - name: nguiland-rest
      dependencies:
        - name: nguiland-dependencies
        - name: nguiland-orm
        - name: nguiland-dto
    - name: nguiland-web-oauth2
      dependencies:
        - name: nguiland-dependencies
