apiVersion: cicd.nguiland.io/v1alpha1
kind: DependencyGraph
metadata:
  name: ngld-maven-lib
  namespace: ${ENVIRONMENT}
spec:
  project: ngld-maven-lib
  repositories:
    - name: nguiland-dependencies
    - name: nguiland-dto
      dependencies:
        - nguiland-dependencies
    - name: nguiland-io-utils
      dependencies:
        - nguiland-dependencies
    - name: nguiland-ms-parent
      dependencies:
        - nguiland-dependencies
    - name: nguiland-orm
      dependencies:
        - nguiland-dependencies
    - name: nguiland-rest
      dependencies:
        - nguiland-dependencies
        - nguiland-orm
        - nguiland-dto
    - name: nguiland-web-oauth2
      dependencies:
        - nguiland-dependencies
